image:
  repository: ishanakhouri/argo-cd-app
  tag: "4ae93dc32a546a1b8151855d6ee9f33d7e5e619a"
  pullPolicy: Always
replicaCount: 2
service:
  type: NodePort
  port: 3000
  nodePort: 30080
imagePullSecrets:
  - name: regcred
rollout:
  enabled: false
