image:
  repository: ishanakhouri/argo-cd-app
  tag: "94f058ecdd51e0d86b439a9a8e9b26bdddf20bce"
  pullPolicy: Always
replicaCount: 2
service:
  type: NodePort
  port: 3000
  nodePort: 30080
imagePullSecrets:
  - name: regcred
rollout:
  enabled: false
